apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-golang
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: golang-test
            image: golang:1.19
            script: |-
              echo "Testing"
              go test ./app
