apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: golang-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: golang-demo
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
    apps.tanzu.vmware.com/pipeline: test-angular
spec:
  source:
    git:
      url: https://github.com/TanzuDK/golang-demo.git
      ref:
        branch: main
